//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAddress
    {
        public EmpAddress()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int AddrId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Pincode { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
