//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EId { get; set; }
        public int EAddrId { get; set; }
        public int ERoleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual EmpAddress EmpAddress { get; set; }
        public virtual EmpRole EmpRole { get; set; }
    }
}
