//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyHabit
    {
        public int HabitId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string HabitName { get; set; }
        public string TargetValue { get; set; }
        public Nullable<System.DateTime> HabitDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public int Streak { get; set; }
    
        public virtual User User { get; set; }
    }
}
