//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Reason { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
