//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LifeOSEntities : DbContext
    {
        public LifeOSEntities()
            : base("name=LifeOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DailyHabit> DailyHabits { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<FocusLog> FocusLogs { get; set; }
        public DbSet<Income> Incomes { get; set; }
        public DbSet<MoodLog> MoodLogs { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
