//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.DailyHabits = new HashSet<DailyHabit>();
            this.Expenses = new HashSet<Expens>();
            this.FocusLogs = new HashSet<FocusLog>();
            this.Incomes = new HashSet<Income>();
            this.MoodLogs = new HashSet<MoodLog>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<DailyHabit> DailyHabits { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<FocusLog> FocusLogs { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<MoodLog> MoodLogs { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
