//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int AssessmentId { get; set; }
        public string ReqNo { get; set; }
        public string AssessmentName { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string AssessmentType { get; set; }
        public string AssessmentSubType { get; set; }
        public int TotalQuestions { get; set; }
        public Nullable<int> UserProgress { get; set; }
        public Nullable<int> ReviewerProgress { get; set; }
        public Nullable<int> ManagerProgress { get; set; }
        public Nullable<int> HRProgress { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EEmployee EEmployee { get; set; }
    }
}
