//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicInfo
    {
        public int Id { get; set; }
        public int Eid { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Gender { get; set; }
        public string NickName { get; set; }
        public string PayType { get; set; }
        public string EmployeeType { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string PersonalEmail { get; set; }
        public string OfficeEmail { get; set; }
        public string HurricanePOCEmail { get; set; }
        public string HurricanePOCPhone { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> ZoneManagerId { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterAddress { get; set; }
        public string HurricaneZone { get; set; }
        public string Competency { get; set; }
        public string LinkedInUrl { get; set; }
        public Nullable<int> PaidOffDaysPerYear { get; set; }
        public string Skills { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
