//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveBalance
    {
        public int LeaveBalanceId { get; set; }
        public int EmployeeId { get; set; }
        public int FinancialYear { get; set; }
        public string LeaveType { get; set; }
        public string Status { get; set; }
        public Nullable<int> BalanceForwardCnt { get; set; }
        public Nullable<int> LeaveCnt { get; set; }
        public Nullable<int> LeavePaidCnt { get; set; }
        public Nullable<int> LeaveWithoutPaidCnt { get; set; }
        public Nullable<int> BalanceLeave { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EEmployee EEmployee { get; set; }
    }
}
