//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeConcessionPass
    {
        public int PassId { get; set; }
        public int EmployeeId { get; set; }
        public string PassNumber { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ValidFromDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Reason { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
