//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaf
    {
        public int LeaveId { get; set; }
        public int EmployeeId { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<bool> IsHalfDayStart { get; set; }
        public Nullable<bool> IsHalfDayEnd { get; set; }
        public decimal TotalLeavesPaid { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string AddressDuringLeave { get; set; }
        public string BackupDuringLeave { get; set; }
        public string PhoneDuringLeave { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> ApprovedByHR { get; set; }
        public string HRNotes { get; set; }
        public string ManagerNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
