//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEmploymentHistory
    {
        public int EmploymentHistoryId { get; set; }
        public int EmployeeId { get; set; }
        public string EmployerName { get; set; }
        public string Designation { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfExit { get; set; }
        public string EmploymentType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ExitReason { get; set; }
        public string RolePerformed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }

        public static implicit operator List<object>(EmployeeEmploymentHistory v)
        {
            throw new NotImplementedException();
        }
    }
}
