//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePaySlip
    {
        public int PaySlipId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime SalaryProcessDate { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal TotalDeduction { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int ActualDays { get; set; }
        public decimal ActualHours { get; set; }
        public Nullable<int> PaidLeaves { get; set; }
        public Nullable<decimal> PaidLeaveHours { get; set; }
        public Nullable<decimal> LeaveWithoutPayHours { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
