//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducationHistory
    {
        public int EducationId { get; set; }
        public int EmployeeId { get; set; }
        public string College { get; set; }
        public string Course { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Grade { get; set; }
        public Nullable<bool> IsInternship { get; set; }
        public string Stream { get; set; }
        public string EducationType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EEmployee EEmployee { get; set; }
    }
}
