//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Assessments = new HashSet<Assessment>();
            this.BasicInfoes = new HashSet<BasicInfo>();
            this.EmployeeBankDetails = new HashSet<EmployeeBankDetail>();
            this.EmployeeConcessionPasses = new HashSet<EmployeeConcessionPass>();
            this.EmployeeDisciplinaryLogs = new HashSet<EmployeeDisciplinaryLog>();
            this.EmployeeEducationHistories = new HashSet<EmployeeEducationHistory>();
            this.EmployeeEmergencyContacts = new HashSet<EmployeeEmergencyContact>();
            this.EmployeeFamilies = new HashSet<EmployeeFamily>();
            this.EmployeeInsurances = new HashSet<EmployeeInsurance>();
            this.EmployeeLicenses = new HashSet<EmployeeLicens>();
            this.EmployeeLoans = new HashSet<EmployeeLoan>();
            this.EmployeePaySlips = new HashSet<EmployeePaySlip>();
            this.EmployeePensions = new HashSet<EmployeePension>();
            this.EmployeeReferences = new HashSet<EmployeeReference>();
            this.EmployeeRemunerations = new HashSet<EmployeeRemuneration>();
            this.EmployeeTimeZones = new HashSet<EmployeeTimeZone>();
            this.EmployeeTrainings = new HashSet<EmployeeTraining>();
            this.EmployeeEmploymentHistories = new HashSet<EmployeeEmploymentHistory>();
            this.EmployeeLeaveBalances = new HashSet<EmployeeLeaveBalance>();
            this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
            this.Logins = new HashSet<Login>();
        }
    
        public int Eid { get; set; }
        public string Ename { get; set; }
        public string Etype { get; set; }
        public string Eaddr { get; set; }
        public string Emob { get; set; }
        public string Edesign { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<BasicInfo> BasicInfoes { get; set; }
        public virtual ICollection<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public virtual ICollection<EmployeeConcessionPass> EmployeeConcessionPasses { get; set; }
        public virtual ICollection<EmployeeDisciplinaryLog> EmployeeDisciplinaryLogs { get; set; }
        public virtual ICollection<EmployeeEducationHistory> EmployeeEducationHistories { get; set; }
        public virtual ICollection<EmployeeEmergencyContact> EmployeeEmergencyContacts { get; set; }
        public virtual ICollection<EmployeeFamily> EmployeeFamilies { get; set; }
        public virtual ICollection<EmployeeInsurance> EmployeeInsurances { get; set; }
        public virtual ICollection<EmployeeLicens> EmployeeLicenses { get; set; }
        public virtual ICollection<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual ICollection<EmployeePaySlip> EmployeePaySlips { get; set; }
        public virtual ICollection<EmployeePension> EmployeePensions { get; set; }
        public virtual ICollection<EmployeeReference> EmployeeReferences { get; set; }
        public virtual ICollection<EmployeeRemuneration> EmployeeRemunerations { get; set; }
        public virtual ICollection<EmployeeTimeZone> EmployeeTimeZones { get; set; }
        public virtual ICollection<EmployeeTraining> EmployeeTrainings { get; set; }
        public virtual ICollection<EmployeeEmploymentHistory> EmployeeEmploymentHistories { get; set; }
        public virtual ICollection<EmployeeLeaveBalance> EmployeeLeaveBalances { get; set; }
        public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
    }
}
