//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDisciplinaryLog
    {
        public int DisciplinaryLogId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string Incident { get; set; }
        public string Brief { get; set; }
        public string HRNotes { get; set; }
        public string ManagerNotes { get; set; }
        public string EmployeeComments { get; set; }
        public Nullable<bool> EmployeeSigned { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
