//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInsurance
    {
        public int InsuranceId { get; set; }
        public int EmployeeId { get; set; }
        public string MemberId { get; set; }
        public string InsuranceName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public string PaySchedule { get; set; }
        public string InsurancePlan { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
