//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFamily
    {
        public int FamilyId { get; set; }
        public int EmployeeId { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Relationship { get; set; }
        public Nullable<bool> IsBIP { get; set; }
        public Nullable<bool> IsNominee { get; set; }
        public Nullable<bool> IsWPDependent { get; set; }
        public string Occupation { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
