//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanmolEntities : DbContext
    {
        public SanmolEntities()
            : base("name=SanmolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Assessment> Assessments { get; set; }
        public DbSet<BasicInfo> BasicInfoes { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public DbSet<EmployeeConcessionPass> EmployeeConcessionPasses { get; set; }
        public DbSet<EmployeeDisciplinaryLog> EmployeeDisciplinaryLogs { get; set; }
        public DbSet<EmployeeEducationHistory> EmployeeEducationHistories { get; set; }
        public DbSet<EmployeeEmergencyContact> EmployeeEmergencyContacts { get; set; }
        public DbSet<EmployeeEmploymentHistory> EmployeeEmploymentHistories { get; set; }
        public DbSet<EmployeeFamily> EmployeeFamilies { get; set; }
        public DbSet<EmployeeInsurance> EmployeeInsurances { get; set; }
        public DbSet<EmployeeLeaveBalance> EmployeeLeaveBalances { get; set; }
        public DbSet<EmployeeLeaf> EmployeeLeaves { get; set; }
        public DbSet<EmployeeLicens> EmployeeLicenses { get; set; }
        public DbSet<EmployeeLoan> EmployeeLoans { get; set; }
        public DbSet<EmployeePaySlip> EmployeePaySlips { get; set; }
        public DbSet<EmployeePension> EmployeePensions { get; set; }
        public DbSet<EmployeeReference> EmployeeReferences { get; set; }
        public DbSet<EmployeeRemuneration> EmployeeRemunerations { get; set; }
        public DbSet<EmployeeTimeZone> EmployeeTimeZones { get; set; }
        public DbSet<EmployeeTraining> EmployeeTrainings { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<registration> registrations { get; set; }
    }
}
