//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanmolEntities : DbContext
    {
        public SanmolEntities()
            : base("name=SanmolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<BasicInfo> BasicInfoes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<EEmployee> EEmployees { get; set; }
        public virtual DbSet<ELogin> ELogins { get; set; }
        public virtual DbSet<EmployeeBankDetail> EmployeeBankDetails { get; set; }
        public virtual DbSet<EmployeeConcessionPass> EmployeeConcessionPasses { get; set; }
        public virtual DbSet<EmployeeDisciplinaryLog> EmployeeDisciplinaryLogs { get; set; }
        public virtual DbSet<EmployeeEducationHistory> EmployeeEducationHistories { get; set; }
        public virtual DbSet<EmployeeEmergencyContact> EmployeeEmergencyContacts { get; set; }
        public virtual DbSet<EmployeeEmploymentHistory> EmployeeEmploymentHistories { get; set; }
        public virtual DbSet<EmployeeFamily> EmployeeFamilies { get; set; }
        public virtual DbSet<EmployeeInsurance> EmployeeInsurances { get; set; }
        public virtual DbSet<EmployeeLeaveBalance> EmployeeLeaveBalances { get; set; }
        public virtual DbSet<EmployeeLeaf> EmployeeLeaves { get; set; }
        public virtual DbSet<EmployeeLicens> EmployeeLicenses { get; set; }
        public virtual DbSet<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual DbSet<EmployeePaySlip> EmployeePaySlips { get; set; }
        public virtual DbSet<EmployeePension> EmployeePensions { get; set; }
        public virtual DbSet<EmployeeReference> EmployeeReferences { get; set; }
        public virtual DbSet<EmployeeRemuneration> EmployeeRemunerations { get; set; }
        public virtual DbSet<EmployeeTimeZone> EmployeeTimeZones { get; set; }
        public virtual DbSet<EmployeeTraining> EmployeeTrainings { get; set; }
        public virtual DbSet<EmployeeTypeMaster> EmployeeTypeMasters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesTypesView> RolesTypesViews { get; set; }
        public virtual DbSet<RoleTypePermission> RoleTypePermissions { get; set; }
        public virtual DbSet<UserRoleMenuView> UserRoleMenuViews { get; set; }
        public virtual DbSet<UserRoleTypePermission> UserRoleTypePermissions { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
