//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTypePermission
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int TypeId { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanRead { get; set; }
        public Nullable<bool> CanUpdate { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Eid { get; set; }
    
        public virtual EmployeeTypeMaster EmployeeTypeMaster { get; set; }
        public virtual Role Role { get; set; }
    }
}
