//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesTypesView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolesTypesView()
        {
            this.UserRoleMenuViews = new HashSet<UserRoleMenuView>();
        }
    
        public int Id { get; set; }
        public int RoleId { get; set; }
        public bool FullTime { get; set; }
        public bool PartTime { get; set; }
        public bool Internship { get; set; }
        public bool Freelance { get; set; }
        public bool Contract { get; set; }
        public bool Temporary { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleMenuView> UserRoleMenuViews { get; set; }
    }
}
