//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleTypePermission
    {
        public int Id { get; set; }
        public int Eid { get; set; }
        public int RoleId { get; set; }
        public int TypeId { get; set; }
        public bool CanCreate { get; set; }
        public bool CanRead { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanDelete { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual EEmployee EEmployee { get; set; }
        public virtual EmployeeTypeMaster EmployeeTypeMaster { get; set; }
        public virtual Role Role { get; set; }
    }
}
