//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMenuView
    {
        public int Id { get; set; }
        public int RoleTypeViewId { get; set; }
        public byte ViewType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual RolesTypesView RolesTypesView { get; set; }
    }
}
