//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanmol_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Cid { get; set; }
        public int CEmpCnt { get; set; }
        public int CWorkDay { get; set; }
    }
}
